-- SCHEMA-BASE-003 (Up)
-- Follow-up to SCHEMA-BASE-002: that pass only covered the 9 tables directly
-- referenced by rls-security.test.ts / dpdp-compliance.test.ts. CI re-run
-- surfaced schema-validation.test.ts and combo-architecture.test.ts, which
-- assert the FULL 42-table Doc #11A MVP baseline plus several columns on
-- tables that already existed on staging in an older shape. This migration
-- closes that remaining gap. STAGING ONLY. Source of truth: production
-- project ufgfznpqixplcbhmsqqw.

-- ---------------------------------------------------------------------
-- Column gaps on tables that already exist on staging
-- ---------------------------------------------------------------------
ALTER TABLE public.dishes
  ADD COLUMN IF NOT EXISTS ingredient_ids integer[] DEFAULT '{}'::integer[],
  ADD COLUMN IF NOT EXISTS is_jain boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS derived_at timestamptz;

ALTER TABLE public.user_category_preferences
  ADD COLUMN IF NOT EXISTS item_id integer,
  ADD COLUMN IF NOT EXISTS preference_bucket text;

-- ---------------------------------------------------------------------
-- tags / dish_tags / dish_similar / meal_ingredients / term_synonyms
-- (Food Knowledge Base)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tags (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL,
  value text NOT NULL,
  display_name text NOT NULL,
  is_food_dna boolean DEFAULT false,
  tier smallint,
  is_user_facing boolean DEFAULT true,
  description text,
  created_at timestamptz DEFAULT now(),
  UNIQUE (category, value)
);
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY tags_select_auth ON public.tags FOR SELECT TO authenticated USING (true);
CREATE POLICY tags_service_write ON public.tags FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.dish_tags (
  dish_id integer NOT NULL REFERENCES public.dishes(id) ON DELETE CASCADE,
  tag_id integer NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
  confidence numeric DEFAULT 1.0,
  created_at timestamptz DEFAULT now(),
  PRIMARY KEY (dish_id, tag_id)
);
CREATE INDEX IF NOT EXISTS idx_dish_tags_dish_id ON public.dish_tags USING btree (dish_id);
ALTER TABLE public.dish_tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY dish_tags_select_auth ON public.dish_tags FOR SELECT TO authenticated USING (true);
CREATE POLICY dish_tags_service_write ON public.dish_tags FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.dish_similar (
  dish_id integer NOT NULL REFERENCES public.dishes(id) ON DELETE CASCADE,
  similar_dish_id integer NOT NULL REFERENCES public.dishes(id) ON DELETE CASCADE,
  similarity_score numeric DEFAULT 0.5,
  created_at timestamptz DEFAULT now(),
  PRIMARY KEY (dish_id, similar_dish_id)
);
ALTER TABLE public.dish_similar ENABLE ROW LEVEL SECURITY;
CREATE POLICY dish_similar_select_auth ON public.dish_similar FOR SELECT TO authenticated USING (true);
CREATE POLICY dish_similar_service_write ON public.dish_similar FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.dish_combo_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  combo_id integer REFERENCES public.dish_combos(id) ON DELETE CASCADE,
  dish_id integer REFERENCES public.dishes(id) ON DELETE RESTRICT,
  role text DEFAULT 'main',
  is_default boolean DEFAULT true,
  is_swappable boolean DEFAULT false,
  display_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.dish_combo_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY dish_combo_items_select_auth ON public.dish_combo_items FOR SELECT TO authenticated USING (true);
CREATE POLICY dish_combo_items_service_write ON public.dish_combo_items FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.meal_ingredients (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dish_id integer REFERENCES public.dishes(id) ON DELETE CASCADE,
  ingredient_id integer REFERENCES public.ingredients(id) ON DELETE RESTRICT,
  display_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  UNIQUE (dish_id, ingredient_id)
);
CREATE INDEX IF NOT EXISTS idx_meal_ingredients_dish ON public.meal_ingredients USING btree (dish_id);
CREATE INDEX IF NOT EXISTS idx_meal_ingredients_ingredient ON public.meal_ingredients USING btree (ingredient_id);
ALTER TABLE public.meal_ingredients ENABLE ROW LEVEL SECURITY;
CREATE POLICY meal_ingredients_select_auth ON public.meal_ingredients FOR SELECT TO authenticated USING (true);
CREATE POLICY meal_ingredients_service_write ON public.meal_ingredients FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.term_synonyms (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canonical_term text NOT NULL,
  synonym text NOT NULL,
  language text DEFAULT 'hi',
  disambiguation_note text,
  created_at timestamptz DEFAULT now(),
  UNIQUE (canonical_term, synonym)
);
ALTER TABLE public.term_synonyms ENABLE ROW LEVEL SECURITY;
CREATE POLICY term_synonyms_select_auth ON public.term_synonyms FOR SELECT TO authenticated USING (true);
CREATE POLICY term_synonyms_service_write ON public.term_synonyms FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------
-- User & Preferences
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_feedback (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  dish_id integer REFERENCES public.dishes(id) ON DELETE SET NULL,
  rating smallint CHECK (rating >= 1 AND rating <= 5),
  feedback text,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.user_feedback ENABLE ROW LEVEL SECURITY;
CREATE POLICY user_feedback_all_own ON public.user_feedback FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_feedback_service_write ON public.user_feedback FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------
-- Planner & RE (keep-empty excluded)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.planner_carousel (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  planner_id uuid REFERENCES public.planner(id) ON DELETE CASCADE,
  meal_slot text NOT NULL CHECK (meal_slot = ANY (ARRAY['breakfast', 'lunch', 'dinner', 'snack'])),
  ref_type text DEFAULT 'dish',
  ref_id integer NOT NULL,
  "position" integer NOT NULL,
  re_score numeric,
  created_at timestamptz DEFAULT now(),
  UNIQUE (planner_id, meal_slot, "position")
);
ALTER TABLE public.planner_carousel ENABLE ROW LEVEL SECURITY;
CREATE POLICY planner_carousel_all_own ON public.planner_carousel
  FOR ALL USING (planner_id IN (SELECT planner.id FROM public.planner WHERE planner.user_id = auth.uid()));
CREATE POLICY planner_carousel_service_write ON public.planner_carousel FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.user_recipe_affinity (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  dish_id integer REFERENCES public.dishes(id) ON DELETE CASCADE,
  affinity numeric DEFAULT 0.5,
  computed_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  static_score numeric(4,2),
  is_eligible boolean NOT NULL DEFAULT false,
  UNIQUE (user_id, dish_id)
);
CREATE INDEX IF NOT EXISTS idx_user_recipe_affinity_eligible ON public.user_recipe_affinity USING btree (user_id) WHERE (is_eligible = true);
ALTER TABLE public.user_recipe_affinity ENABLE ROW LEVEL SECURITY;
CREATE POLICY recipe_affinity_all_own ON public.user_recipe_affinity FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_recipe_affinity_service_write ON public.user_recipe_affinity FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.recommendation_debug_log (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  plan_date date NOT NULL,
  meal_slot text NOT NULL,
  dish_id integer,
  score_breakdown jsonb NOT NULL,
  re_version text DEFAULT 'v1',
  created_at timestamptz DEFAULT now(),
  final_score numeric(4,2),
  weather_input jsonb,
  eligible_pool_size integer
);
ALTER TABLE public.recommendation_debug_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY debug_log_select_own ON public.recommendation_debug_log FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY recommendation_debug_service_write ON public.recommendation_debug_log FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.user_dish_patterns (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  dish_id integer REFERENCES public.dishes(id) ON DELETE CASCADE,
  preferred_slots text[] DEFAULT '{}'::text[],
  preferred_days text[] DEFAULT '{}'::text[],
  frequency text DEFAULT '0',
  last_accepted timestamptz,
  computed_at timestamptz DEFAULT now(),
  last_suggested date,
  acceptance_count integer NOT NULL DEFAULT 0,
  rejection_count integer NOT NULL DEFAULT 0,
  UNIQUE (user_id, dish_id)
);
ALTER TABLE public.user_dish_patterns ENABLE ROW LEVEL SECURITY;
CREATE POLICY dish_patterns_all_own ON public.user_dish_patterns FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_dish_patterns_service_write ON public.user_dish_patterns FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.weather_cache (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  city text NOT NULL UNIQUE,
  state text,
  weather_code integer,
  temp_celsius numeric,
  description text,
  fetched_at timestamptz DEFAULT now(),
  expires_at timestamptz NOT NULL
);
ALTER TABLE public.weather_cache ENABLE ROW LEVEL SECURITY;
CREATE POLICY weather_cache_select_auth ON public.weather_cache FOR SELECT TO authenticated USING (true);
CREATE POLICY weather_cache_service_write ON public.weather_cache FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.region_food_affinity (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state_code text NOT NULL,
  cuisine_id integer REFERENCES public.cuisines(id) ON DELETE CASCADE,
  affinity_score numeric NOT NULL DEFAULT 0.5,
  created_at timestamptz DEFAULT now(),
  is_primary boolean NOT NULL DEFAULT false,
  UNIQUE (state_code, cuisine_id)
);
CREATE INDEX IF NOT EXISTS idx_region_affinity_state ON public.region_food_affinity USING btree (state_code);
ALTER TABLE public.region_food_affinity ENABLE ROW LEVEL SECURITY;
CREATE POLICY region_affinity_select_auth ON public.region_food_affinity FOR SELECT TO authenticated USING (true);
CREATE POLICY region_affinity_service_write ON public.region_food_affinity FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------
-- App Intelligence
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.app_events (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  event_type text NOT NULL,
  screen text,
  device_info text,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  session_id uuid,
  device_type text CHECK (device_type = ANY (ARRAY['android', 'ios', 'web'])),
  app_version text
);
CREATE INDEX IF NOT EXISTS idx_app_events_user_date ON public.app_events USING btree (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_app_events_type ON public.app_events USING btree (event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_app_events_created_at ON public.app_events USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_app_events_session ON public.app_events USING btree (session_id) WHERE (session_id IS NOT NULL);
ALTER TABLE public.app_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY app_events_all_own ON public.app_events FOR ALL USING (auth.uid() = user_id);
CREATE POLICY app_events_service_write ON public.app_events FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.user_behavioral_profile (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE,
  total_suggestions integer DEFAULT 0,
  total_accepted integer DEFAULT 0,
  total_rejected integer DEFAULT 0,
  total_never integer DEFAULT 0,
  total_not_today integer DEFAULT 0,
  breakfast_rate numeric DEFAULT 0,
  lunch_rate numeric DEFAULT 0,
  dinner_rate numeric DEFAULT 0,
  feature_usage jsonb DEFAULT '{}'::jsonb,
  last_computed_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  cuisine_acceptance_dist jsonb,
  cooking_method_dist jsonb,
  texture_dist jsonb,
  spice_dist jsonb,
  avg_session_duration numeric,
  sessions_per_week numeric,
  primary_meal_slot text,
  days_active integer DEFAULT 0
);
ALTER TABLE public.user_behavioral_profile ENABLE ROW LEVEL SECURITY;
CREATE POLICY behavioral_profile_all_own ON public.user_behavioral_profile FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_behavioral_profile_service_write ON public.user_behavioral_profile FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.experiments (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  description text,
  variants jsonb NOT NULL,
  is_active boolean DEFAULT false,
  start_date timestamptz,
  end_date timestamptz,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.experiments ENABLE ROW LEVEL SECURITY;
CREATE POLICY experiments_select_auth ON public.experiments FOR SELECT TO authenticated USING (true);
CREATE POLICY experiments_service_write ON public.experiments FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.experiment_assignments (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  experiment_id uuid REFERENCES public.experiments(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  variant text NOT NULL,
  assigned_at timestamptz DEFAULT now(),
  UNIQUE (experiment_id, user_id)
);
ALTER TABLE public.experiment_assignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY experiment_assignments_select_own ON public.experiment_assignments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY experiment_assignments_service_write ON public.experiment_assignments FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------
-- Operations
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.role_audit (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid,
  changed_by uuid,
  old_role text,
  new_role text,
  reason text,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.role_audit ENABLE ROW LEVEL SECURITY;
CREATE POLICY role_audit_service_only ON public.role_audit FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.etl_jobs (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  job_name text NOT NULL,
  status text DEFAULT 'pending' CHECK (status = ANY (ARRAY['pending', 'running', 'completed', 'partial', 'failed'])),
  started_at timestamptz,
  completed_at timestamptz,
  rows_processed integer,
  error_message text,
  metadata jsonb,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.etl_jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY etl_jobs_service_only ON public.etl_jobs FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.cache_metadata (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  cache_key text NOT NULL UNIQUE,
  cached_at timestamptz DEFAULT now(),
  expires_at timestamptz NOT NULL,
  metadata jsonb
);
ALTER TABLE public.cache_metadata ENABLE ROW LEVEL SECURITY;
CREATE POLICY cache_metadata_service_only ON public.cache_metadata FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.mv_refresh_history (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  view_name text NOT NULL,
  refreshed_at timestamptz DEFAULT now(),
  duration_ms integer,
  status text DEFAULT 'success'
);
ALTER TABLE public.mv_refresh_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY mv_refresh_history_service_only ON public.mv_refresh_history FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.media_assets (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  asset_type text NOT NULL,
  url text NOT NULL,
  cdn_url text,
  blurhash text,
  width integer,
  height integer,
  file_size integer,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.media_assets ENABLE ROW LEVEL SECURITY;
CREATE POLICY media_assets_select_auth ON public.media_assets FOR SELECT TO authenticated USING (true);
CREATE POLICY media_assets_service_write ON public.media_assets FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.migration_log (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  migration_name text NOT NULL,
  applied_at timestamptz DEFAULT now(),
  notes text
);
ALTER TABLE public.migration_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY migration_log_service_only ON public.migration_log FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.notification_log (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  notification_type text NOT NULL,
  sent_at timestamptz DEFAULT now(),
  opened boolean DEFAULT false,
  opened_at timestamptz
);
ALTER TABLE public.notification_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY notification_log_select_own ON public.notification_log FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY notification_log_service_write ON public.notification_log FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------
-- Keep-Empty tables (recipes, recipe_steps, family_members)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.recipes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dish_id integer REFERENCES public.dishes(id) ON DELETE CASCADE,
  version integer DEFAULT 1,
  is_active boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;
CREATE POLICY recipes_select_auth ON public.recipes FOR SELECT TO authenticated USING (true);
CREATE POLICY recipes_service_write ON public.recipes FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.recipe_steps (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id integer REFERENCES public.recipes(id) ON DELETE CASCADE,
  step_number integer NOT NULL,
  instruction text NOT NULL,
  duration_mins integer,
  tools text[],
  ingredients_mentioned integer[],
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.recipe_steps ENABLE ROW LEVEL SECURITY;
CREATE POLICY recipe_steps_select_auth ON public.recipe_steps FOR SELECT TO authenticated USING (true);
CREATE POLICY recipe_steps_service_write ON public.recipe_steps FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.family_members (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  name text NOT NULL,
  food_pref text,
  age integer,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.family_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY family_members_all_own ON public.family_members FOR ALL USING (auth.uid() = user_id);
CREATE POLICY family_members_service_write ON public.family_members FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------
-- dish_popularity materialized view (depends on suggestion_logs)
-- ---------------------------------------------------------------------
CREATE MATERIALIZED VIEW IF NOT EXISTS public.dish_popularity AS
SELECT
  dish_id,
  count(*) FILTER (WHERE action = 'accepted') AS total_accepted,
  count(*) FILTER (WHERE action = 'rejected') AS total_rejected,
  count(*) FILTER (WHERE action = 'never') AS total_never,
  count(*) AS total_suggestions,
  round((count(*) FILTER (WHERE action = 'accepted'))::numeric / NULLIF(count(*), 0)::numeric * 100, 2) AS acceptance_rate,
  mode() WITHIN GROUP (ORDER BY meal_slot) AS best_slot,
  mode() WITHIN GROUP (ORDER BY EXTRACT(dow FROM plan_date)) AS best_day_of_week,
  max(created_at) AS last_suggested
FROM public.suggestion_logs
WHERE dish_id IS NOT NULL
GROUP BY dish_id;
