-- SCHEMA-BASE-002 (Up)
-- Replicates the legacy MVP baseline tables (originally applied to production
-- pre-ledger under SCHEMA-BASE-001, never captured in a migration file) onto
-- foofoo-staging so the MVP-scope test suite (rls-security.test.ts,
-- dpdp-compliance.test.ts) has the schema it expects. STAGING ONLY.
-- Source of truth for column/constraint/policy definitions: production
-- project ufgfznpqixplcbhmsqqw (introspected via information_schema /
-- pg_constraint / pg_policies / pg_indexes).

-- ---------------------------------------------------------------------
-- cuisine_groups (dependency of cuisines.cuisine_group)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cuisine_groups (
  name text PRIMARY KEY,
  display_name text NOT NULL,
  display_order integer DEFAULT 0,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.cuisine_groups ENABLE ROW LEVEL SECURITY;

CREATE POLICY cuisine_groups_select_auth ON public.cuisine_groups
  FOR SELECT TO authenticated USING (true);
CREATE POLICY cuisine_groups_service_write ON public.cuisine_groups
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------
-- cuisines
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cuisines (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  display_name text NOT NULL,
  cuisine_group text REFERENCES public.cuisine_groups(name),
  parent_cuisine integer REFERENCES public.cuisines(id),
  state_origin text,
  description text,
  icon_url text,
  tier text DEFAULT 'tier_2' CHECK (tier = ANY (ARRAY['tier_1', 'tier_2', 'tier_3'])),
  is_user_facing boolean DEFAULT true,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.cuisines ENABLE ROW LEVEL SECURITY;

CREATE POLICY cuisines_select_auth ON public.cuisines
  FOR SELECT TO authenticated USING (true);
CREATE POLICY cuisines_service_write ON public.cuisines
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------
-- dish_combos (dependency of suggestion_logs.combo_id)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dish_combos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  meal_types text[] DEFAULT '{}',
  cuisine_id integer REFERENCES public.cuisines(id),
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  combo_type text CHECK (combo_type = ANY (ARRAY['inseparable', 'base_with_sides', 'thali']))
);

ALTER TABLE public.dish_combos ENABLE ROW LEVEL SECURITY;

CREATE POLICY dish_combos_select_auth ON public.dish_combos
  FOR SELECT TO authenticated USING (true);
CREATE POLICY dish_combos_service_write ON public.dish_combos
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------
-- ingredients
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ingredients (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  category text NOT NULL CHECK (category = ANY (ARRAY[
    'spice', 'vegetable', 'leafy_green', 'lentil_legume', 'grain_flour',
    'dairy', 'meat', 'seafood', 'egg', 'oil_fat', 'nut_seed', 'fruit',
    'sweetener', 'herb_aromatic', 'condiment'
  ])),
  is_veg boolean DEFAULT true,
  is_vegan boolean DEFAULT true,
  is_jain_compatible boolean DEFAULT true,
  is_gluten boolean DEFAULT false,
  is_dairy boolean DEFAULT false,
  is_nut boolean DEFAULT false,
  is_egg boolean DEFAULT false,
  is_shellfish boolean DEFAULT false,
  is_soy boolean DEFAULT false,
  standard_unit varchar(32),
  unit_conversion jsonb,
  season_months text[],
  description text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.ingredients ENABLE ROW LEVEL SECURITY;

CREATE POLICY ingredients_select_auth ON public.ingredients
  FOR SELECT TO authenticated USING (true);
CREATE POLICY ingredients_service_write ON public.ingredients
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------
-- planner
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.planner (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  plan_date date NOT NULL,
  breakfast_ref_type text DEFAULT 'dish',
  breakfast_ref_id integer,
  lunch_ref_type text DEFAULT 'dish',
  lunch_ref_id integer,
  dinner_ref_type text DEFAULT 'dish',
  dinner_ref_id integer,
  snacks_ref_type text DEFAULT 'dish',
  snacks_ref_id integer,
  locked_slots text[] DEFAULT '{}',
  generated_at timestamptz DEFAULT now(),
  re_version text DEFAULT 'v1',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE (user_id, plan_date)
);

ALTER TABLE public.planner ENABLE ROW LEVEL SECURITY;

CREATE POLICY planner_all_own ON public.planner
  FOR ALL USING (auth.uid() = user_id);
CREATE POLICY planner_service_write ON public.planner
  FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_planner_user_date ON public.planner USING btree (user_id, plan_date DESC);

-- ---------------------------------------------------------------------
-- never_list
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.never_list (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  dish_id integer REFERENCES public.dishes(id) ON DELETE CASCADE,
  reason text,
  created_at timestamptz DEFAULT now(),
  ref_type text CHECK (ref_type = ANY (ARRAY['dish', 'combo', 'ingredient'])),
  is_active boolean NOT NULL DEFAULT true,
  reactivation_trigger text,
  UNIQUE (user_id, dish_id)
);

ALTER TABLE public.never_list ENABLE ROW LEVEL SECURITY;

CREATE POLICY never_list_all_own ON public.never_list
  FOR ALL USING (auth.uid() = user_id);
CREATE POLICY never_list_service_write ON public.never_list
  FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_never_list_user ON public.never_list USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_never_list_user_active ON public.never_list USING btree (user_id) WHERE (is_active = true);

-- ---------------------------------------------------------------------
-- suggestion_logs
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.suggestion_logs (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  dish_id integer REFERENCES public.dishes(id) ON DELETE SET NULL,
  combo_id integer REFERENCES public.dish_combos(id) ON DELETE SET NULL,
  plan_date date NOT NULL,
  meal_slot text NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY[
    'accepted', 'rejected', 'shown', 'viewed', 'swiped', 'swiped_to',
    'swiped_past', 'locked', 'unlocked', 'never', 'not_today',
    'tapped_detail', 'tapped_ingredients', 'added_to_date', 'refresh'
  ])),
  position integer,
  re_version text DEFAULT 'v1',
  re_score numeric,
  created_at timestamptz DEFAULT now(),
  ref_type text CHECK (ref_type = ANY (ARRAY['dish', 'combo']))
);

ALTER TABLE public.suggestion_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY suggestion_logs_insert_own ON public.suggestion_logs
  FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY suggestion_logs_select_own ON public.suggestion_logs
  FOR SELECT USING (user_id = auth.uid() OR user_id IS NULL);
CREATE POLICY suggestion_logs_service_write ON public.suggestion_logs
  FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_suggestion_logs_user_date ON public.suggestion_logs USING btree (user_id, plan_date DESC);
CREATE INDEX IF NOT EXISTS idx_suggestion_logs_dish_action ON public.suggestion_logs USING btree (dish_id, action);

-- ---------------------------------------------------------------------
-- user_inferred_prefs
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_inferred_prefs (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE,
  spice_score numeric DEFAULT 0,
  texture_score jsonb DEFAULT '{}',
  complexity_score numeric DEFAULT 0,
  repeat_tolerance numeric DEFAULT 0.5,
  cuisine_drift jsonb DEFAULT '{}',
  decay_config jsonb DEFAULT '{"beyond": 0.05, "week_1": 1.0, "week_2_4": 0.5, "month_2_3": 0.2}',
  computed_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  sweetness_tolerance numeric,
  repeat_tolerance_breakfast numeric DEFAULT 0.5,
  repeat_tolerance_lunch numeric DEFAULT 0.5,
  repeat_tolerance_dinner numeric DEFAULT 0.5,
  coherence_sensitivity numeric DEFAULT 0.5,
  cooking_method_prefs jsonb,
  richness_pref text
);

ALTER TABLE public.user_inferred_prefs ENABLE ROW LEVEL SECURITY;

CREATE POLICY user_inferred_prefs_all_own ON public.user_inferred_prefs
  FOR ALL USING (auth.uid() = user_id);
CREATE POLICY user_inferred_prefs_service_write ON public.user_inferred_prefs
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------
-- audit_log
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.audit_log (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid,
  action text NOT NULL,
  ip_address text,
  user_agent text,
  device_info text,
  metadata jsonb,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY audit_log_service_only ON public.audit_log
  FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_audit_log_user_created ON public.audit_log USING btree (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_user_date ON public.audit_log USING btree (user_id, created_at DESC);
