#!/usr/bin/env ts-node
/**
 * re-report-generator.ts
 *
 * Runs the RE persona suite (light mode) and renders:
 *   - reports/md/re-summary-YYYY-MM-DD.md            — master summary
 *   - reports/md/personas/RPxxx-<slug>.md             — per-persona reports
 *   - reports/html/re-report-YYYY-MM-DD.html           — HTML dashboard
 *
 * Run: npm run report:re
 */

import * as fs from 'fs';
import * as path from 'path';
import { runAllPersonas, REPersonaResult, REPersonaRunSummary } from '../personas/re-persona-runner';
import { GATES } from '../config/success-gates';
import { RE_PERSONAS } from '../personas/re-persona-definitions';

function slug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

// ─── Markdown ─────────────────────────────────────────────────────────────────

export function buildMasterMarkdown(summary: REPersonaRunSummary): string {
  const L: string[] = [];
  L.push('# FooFoo RE — Persona Validation Summary', '');
  L.push(`> Generated: ${summary.runDate}  `);
  L.push(`> Mode: \`${summary.mode}\`  `);
  L.push(`> Duration: ${(summary.durationMs / 1000).toFixed(1)}s`, '');
  L.push('## Gates', '');
  L.push(`- Hard constraint violations (max): ${GATES.HARD_CONSTRAINT_VIOLATIONS_MAX}`);
  L.push(`- Min dishes / slot: ${GATES.MIN_DISHES_PER_SLOT}`);
  L.push(`- Cultural match (min): ${GATES.CULTURAL_MATCH_MIN}`, '');
  L.push('## Summary', '');
  L.push('| Metric | Value |');
  L.push('|--------|-------|');
  L.push(`| Total personas | ${summary.totalPersonas} |`);
  L.push(`| Passed | ${summary.passed} |`);
  L.push(`| Failed | ${summary.failed} |`);
  L.push(`| Skipped | ${summary.skipped} |`);
  L.push(`| Hard constraint violations | ${summary.hardConstraintViolations} |`, '');
  L.push('## Per-persona results', '');
  L.push('| ID | Name | Status | Dishes/slot | Region (match) | Cultural | Violations |');
  L.push('|----|------|--------|-------------|----------------|----------|------------|');
  for (const r of summary.results) {
    const status = r.skipped ? '○ SKIP' : r.passed ? '✓ PASS' : '✗ FAIL';
    L.push(
      `| ${r.personaId} | ${r.personaName} | ${status} | ${r.dishCountPerSlot} | ${r.actualRegionArchetype} (${r.regionArchetypeMatch ? 'match' : 'diff'}) | ${r.culturalScore.toFixed(2)} | ${r.hardConstraintViolations} |`,
    );
  }
  const failed = summary.results.filter((r) => !r.passed && !r.skipped);
  if (failed.length) {
    L.push('', '## Failures', '');
    for (const r of failed) {
      L.push(`### ${r.personaId} — ${r.personaName}`);
      for (const e of r.errors) L.push(`- ${e}`);
      L.push('');
    }
  }
  L.push('', '---', '*Generated by re-report-generator.ts*');
  return L.join('\n');
}

export function buildPersonaMarkdown(r: REPersonaResult): string {
  const persona = RE_PERSONAS.find((p) => p.id === r.personaId);
  const L: string[] = [];
  L.push(`# ${r.personaId} — ${r.personaName}`, '');
  if (persona) {
    L.push(`- Home state: ${persona.homeStateId} → ${persona.currentCity}`);
    L.push(`- Food pref: ${persona.foodPref}`);
    L.push(`- Household: ${persona.householdSize} (${persona.members.map((m) => m.role).join(', ')})`);
    L.push(`- Feedback script: ${persona.feedbackScript}`);
    L.push(`- Cultural note: ${persona.expects.culturalNote}`, '');
  }
  L.push('## Result', '');
  L.push(`- Status: ${r.skipped ? 'SKIPPED' : r.passed ? 'PASS' : 'FAIL'}`);
  L.push(`- Dishes/slot: ${r.dishCountPerSlot}`);
  L.push(`- Region archetype: ${r.actualRegionArchetype} (${r.regionArchetypeMatch ? 'match' : 'differs'})`);
  L.push(`- Cultural score: ${r.culturalScore.toFixed(2)}`);
  L.push(`- Hard constraint violations: ${r.hardConstraintViolations}`);
  L.push(`- Forbidden diet types found: ${r.forbiddenDietTypesFound.join(', ') || 'none'}`);
  L.push(`- Add-on segments expected: ${r.addonSegmentsExpected.join(', ') || 'none'}`);
  L.push(`- Add-on segments found: ${r.addonSegmentsFound.join(', ') || 'none'}`);
  if (r.errors.length) { L.push('', '### Errors'); r.errors.forEach((e) => L.push(`- ${e}`)); }
  if (r.warnings.length) { L.push('', '### Warnings'); r.warnings.forEach((w) => L.push(`- ${w}`)); }
  return L.join('\n');
}

// ─── HTML ─────────────────────────────────────────────────────────────────────

export function buildHtml(summary: REPersonaRunSummary): string {
  const rows = summary.results
    .map((r) => {
      const color = r.skipped ? '#64748b' : r.passed ? '#16a34a' : '#dc2626';
      const bg = r.skipped ? '#f1f5f9' : r.passed ? '#f0fdf4' : '#fef2f2';
      const status = r.skipped ? 'SKIP' : r.passed ? 'PASS' : 'FAIL';
      return `<tr style="background:${bg}">
        <td><b>${r.personaId}</b></td><td>${r.personaName}</td>
        <td style="color:${color};font-weight:700">${status}</td>
        <td>${r.dishCountPerSlot}</td>
        <td>${r.actualRegionArchetype} ${r.regionArchetypeMatch ? '✓' : '≈'}</td>
        <td>${r.culturalScore.toFixed(2)}</td>
        <td>${r.hardConstraintViolations}</td></tr>`;
    })
    .join('\n');
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>FooFoo RE Persona Dashboard</title>
<style>
 body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f8fafc;color:#1e293b;margin:0}
 .header{background:linear-gradient(135deg,#2D6A4F,#FF6B35);color:#fff;padding:24px 32px}
 .header h1{margin:0;font-size:1.6rem} .container{max-width:1200px;margin:0 auto;padding:24px 32px}
 .cards{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:24px}
 .card{background:#fff;border-radius:12px;padding:16px;box-shadow:0 1px 3px rgba(0,0,0,.08)}
 .card .n{font-size:2rem;font-weight:800} .card .l{font-size:.8rem;color:#64748b}
 table{width:100%;border-collapse:collapse;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.08)}
 th{text-align:left;padding:10px 12px;background:#f1f5f9;color:#475569} td{padding:10px 12px;border-bottom:1px solid #f1f5f9}
</style></head><body>
<div class="header"><h1>🍱 FooFoo — RE Persona Validation</h1>
<p>Mode: ${summary.mode} · ${summary.totalPersonas} personas · ${summary.runDate}</p></div>
<div class="container">
 <div class="cards">
  <div class="card"><div class="n">${summary.totalPersonas}</div><div class="l">Total</div></div>
  <div class="card"><div class="n" style="color:#16a34a">${summary.passed}</div><div class="l">Passed</div></div>
  <div class="card"><div class="n" style="color:#dc2626">${summary.failed}</div><div class="l">Failed</div></div>
  <div class="card"><div class="n" style="color:#64748b">${summary.skipped}</div><div class="l">Skipped</div></div>
  <div class="card"><div class="n" style="color:#dc2626">${summary.hardConstraintViolations}</div><div class="l">Hard Violations</div></div>
 </div>
 <table><thead><tr><th>ID</th><th>Name</th><th>Status</th><th>Dishes/slot</th><th>Region</th><th>Cultural</th><th>Violations</th></tr></thead>
 <tbody>${rows}</tbody></table>
</div></body></html>`;
}

// ─── Orchestration ────────────────────────────────────────────────────────────

export async function generateReports(
  summary?: REPersonaRunSummary,
): Promise<{ mdPath: string; htmlPath: string; personaDir: string }> {
  const run = summary ?? (await runAllPersonas('light'));

  const reportsDir = path.resolve(__dirname);
  const mdDir = path.join(reportsDir, 'md');
  const personaDir = path.join(mdDir, 'personas');
  const htmlDir = path.join(reportsDir, 'html');
  for (const d of [mdDir, personaDir, htmlDir]) {
    if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true });
  }

  const date = today();
  const mdPath = path.join(mdDir, `re-summary-${date}.md`);
  fs.writeFileSync(mdPath, buildMasterMarkdown(run), 'utf8');

  for (const r of run.results) {
    const file = path.join(personaDir, `${r.personaId}-${slug(r.personaName)}.md`);
    fs.writeFileSync(file, buildPersonaMarkdown(r), 'utf8');
  }

  const htmlPath = path.join(htmlDir, `re-report-${date}.html`);
  fs.writeFileSync(htmlPath, buildHtml(run), 'utf8');

  return { mdPath, htmlPath, personaDir };
}

if (require.main === module) {
  generateReports()
    .then(({ mdPath, htmlPath, personaDir }) => {
      // eslint-disable-next-line no-console
      console.log(`RE reports written:\n  ${mdPath}\n  ${htmlPath}\n  ${personaDir}/`);
    })
    .catch((err) => {
      // eslint-disable-next-line no-console
      console.error('re-report-generator failed:', err);
      process.exit(1);
    });
}
